[package]
authors = ["Filip Demski <glamhoth@protonmail.com>"]
edition = "2021"
name = "test-event-cancellation"
version = "0.1.0"

[dependencies]
aerugo = { version = "0.1.0", path = "../..", features = ["use-aerugo-x86"] }
